NICF:
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 300
PTS:
  - num_particles: 2
    var: 0.5
    var_u: 1.0
    var_v: 1.0
    num_lat: 2
COFIBA:
  - alpha: 1
    alpha_2: 1
    num_lat: 10
ThompsonSampling:
  - alpha_0: 1
    beta_0: 1
Random:
kNNBandit:
ALMostPopular:
OurMethod1:
  - alpha: 1.0
    stop: null
    weight_method: 'change'
    num_lat: 10
OurMethod2:
  - alpha: 1.0
    num_lat: 10
MostPopular:
LinearUCB:
  - var: 0.05
    user_var: 0.01
    item_var: 0.01
    stop_criteria: 0.0009
    iterations: 20
    alpha: 1.0
    num_lat: 10
LinEGreedy:
  - epsilon: 0.1
    num_lat: 10
LinUCB:
  - alpha: 1.0
    num_lat: 10
PPELPE:
UCBLearner:
  - stop: 14
    num_lat: 10
GLM_UCB:
  - c: 1.0
    num_lat: 10
LinearEGreedy:
  - var: 0.05
    user_var: 0.01
    item_var: 0.01
    stop_criteria: 0.0009
    iterations: 20
    num_lat: 10
LinearThompsonSampling:
  - var: 0.05
    user_var: 0.01
    item_var: 0.01
    stop_criteria: 0.0009
    iterations: 20
    num_lat: 10
EGreedy:
  - epsilon: 0.4
  - epsilon: 0.3
  - epsilon: 0.2
  - epsilon: 0.1
  - epsilon: 0.05
  - epsilon: 0.01
UCB:
  - c: 1.5
  - c: 1.0
  - c: 0.7
  - c: 0.5
  - c: 0.3
  - c: 0.1
MostRepresentative:
ALEntropy:
Entropy0:
HELF:
PopPlusEnt:
DistinctPopular:
EMostPopular:
  - epsilon: 0.2
Entropy:
LogPopEnt:
TinUCB:
  - alpha: 0.2
