NICF:
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 10
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 20
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 30
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 40
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.1
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.01
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
  - batch: 128
    clip_param: 0.2
    dropout_rate: 0.1
    gamma: 0.0
    inner_epoch: 50
    latent_factor: 50
    learning_rate: 0.0001
    num_blocks: 2
    num_heads: 1
    restore_model: false
    rnn_layer: 1
    time_step: 3
    training_epoch: 30000
PTS:
  - num_lat: 5
    num_particles: 2
    var: 0.5
    var_u: 1.0
    var_v: 1.0
  - num_lat: 5
    num_particles: 5
    var: 0.5
    var_u: 1.0
    var_v: 1.0
  - num_lat: 10
    num_particles: 2
    var: 0.5
    var_u: 1.0
    var_v: 1.0
  - num_lat: 10
    num_particles: 5
    var: 0.5
    var_u: 1.0
    var_v: 1.0
  - num_lat: 20
    num_particles: 2
    var: 0.5
    var_u: 1.0
    var_v: 1.0
  - num_lat: 20
    num_particles: 5
    var: 0.5
    var_u: 1.0
    var_v: 1.0
COFIBA:
  - alpha: 1
    alpha_2: 1
    num_lat: 10
ThompsonSampling:
  - alpha_0: 1
    beta_0: 1
  - alpha_0: 1
    beta_0: 10
  - alpha_0: 1
    beta_0: 100
Random:
kNNBandit:
ALMostPopular:
OurMethod1:
  - alpha: 0.25
    num_lat: 10
    stop: null
    weight_method: change
  - alpha: 0.25
    num_lat: 20
    stop: null
    weight_method: change
  - alpha: 0.25
    num_lat: 30
    stop: null
    weight_method: change
  - alpha: 0.25
    num_lat: 40
    stop: null
    weight_method: change
  - alpha: 0.25
    num_lat: 50
    stop: null
    weight_method: change
  - alpha: 0.5
    num_lat: 10
    stop: null
    weight_method: change
  - alpha: 0.5
    num_lat: 20
    stop: null
    weight_method: change
  - alpha: 0.5
    num_lat: 30
    stop: null
    weight_method: change
  - alpha: 0.5
    num_lat: 40
    stop: null
    weight_method: change
  - alpha: 0.5
    num_lat: 50
    stop: null
    weight_method: change
  - alpha: 0.75
    num_lat: 10
    stop: null
    weight_method: change
  - alpha: 0.75
    num_lat: 20
    stop: null
    weight_method: change
  - alpha: 0.75
    num_lat: 30
    stop: null
    weight_method: change
  - alpha: 0.75
    num_lat: 40
    stop: null
    weight_method: change
  - alpha: 0.75
    num_lat: 50
    stop: null
    weight_method: change
  - alpha: 1
    num_lat: 10
    stop: null
    weight_method: change
  - alpha: 1
    num_lat: 20
    stop: null
    weight_method: change
  - alpha: 1
    num_lat: 30
    stop: null
    weight_method: change
  - alpha: 1
    num_lat: 40
    stop: null
    weight_method: change
  - alpha: 1
    num_lat: 50
    stop: null
    weight_method: change

OurMethod2:
  - alpha: 0.25
    num_lat: 5
  - alpha: 0.5
    num_lat: 5
  - alpha: 0.75
    num_lat: 5
  - alpha: 1
    num_lat: 5
  - alpha: 0.25
    num_lat: 10
  - alpha: 0.5
    num_lat: 10
  - alpha: 0.75
    num_lat: 10
  - alpha: 1
    num_lat: 10
  - alpha: 0.25
    num_lat: 20
  - alpha: 0.5
    num_lat: 20
  - alpha: 0.75
    num_lat: 20
  - alpha: 1
    num_lat: 20

MostPopular:
LinearUCB:
  - alpha: 0.25
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.75
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 1
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.25
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.75
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 1
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.25
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 0.75
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - alpha: 1
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05


LinEGreedy:
  - epsilon: 0.1
    num_lat: 10
  - epsilon: 0.1
    num_lat: 20
  - epsilon: 0.1
    num_lat: 30
  - epsilon: 0.1
    num_lat: 40
  - epsilon: 0.1
    num_lat: 50
  - epsilon: 0.2
    num_lat: 10
  - epsilon: 0.2
    num_lat: 20
  - epsilon: 0.2
    num_lat: 30
  - epsilon: 0.2
    num_lat: 40
  - epsilon: 0.2
    num_lat: 50
  - epsilon: 0.3
    num_lat: 10
  - epsilon: 0.3
    num_lat: 20
  - epsilon: 0.3
    num_lat: 30
  - epsilon: 0.3
    num_lat: 40
  - epsilon: 0.3
    num_lat: 50
  - epsilon: 0.4
    num_lat: 10
  - epsilon: 0.4
    num_lat: 20
  - epsilon: 0.4
    num_lat: 30
  - epsilon: 0.4
    num_lat: 40
  - epsilon: 0.4
    num_lat: 50
  - epsilon: 0.5
    num_lat: 10
  - epsilon: 0.5
    num_lat: 20
  - epsilon: 0.5
    num_lat: 30
  - epsilon: 0.5
    num_lat: 40
  - epsilon: 0.5
    num_lat: 50
LinUCB:
  - alpha: 0.25
    num_lat: 10
  - alpha: 0.25
    num_lat: 20
  - alpha: 0.25
    num_lat: 30
  - alpha: 0.25
    num_lat: 40
  - alpha: 0.25
    num_lat: 50
  - alpha: 0.5
    num_lat: 10
  - alpha: 0.5
    num_lat: 20
  - alpha: 0.5
    num_lat: 30
  - alpha: 0.5
    num_lat: 40
  - alpha: 0.5
    num_lat: 50
  - alpha: 0.75
    num_lat: 10
  - alpha: 0.75
    num_lat: 20
  - alpha: 0.75
    num_lat: 30
  - alpha: 0.75
    num_lat: 40
  - alpha: 0.75
    num_lat: 50
  - alpha: 1
    num_lat: 10
  - alpha: 1
    num_lat: 20
  - alpha: 1
    num_lat: 30
  - alpha: 1
    num_lat: 40
  - alpha: 1
    num_lat: 50
PPELPE:
UCBLearner:
  - stop: 14
    num_lat: 10
GLM_UCB:
  - c: 1.0
    num_lat: 10
LinearEGreedy:
  - epsilon: 0.1
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.2
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.3
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.4
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 5
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.1
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.2
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.3
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.4
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 10
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.1
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.2
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.3
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.4
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05
  - epsilon: 0.5
    item_var: 0.01
    iterations: 20
    num_lat: 20
    stop_criteria: 0.0009
    user_var: 0.01
    var: 0.05

LinearThompsonSampling:
  - var: 0.05
    user_var: 0.01
    item_var: 0.01
    stop_criteria: 0.0009
    iterations: 20
    num_lat: 10
EGreedy:
  - epsilon: 0.4
  - epsilon: 0.3
  - epsilon: 0.2
  - epsilon: 0.1
  - epsilon: 0.05
  - epsilon: 0.01
UCB:
  - c: 1.0
  - c: 0.75
  - c: 0.5
  - c: 0.25
MostRepresentative:
ALEntropy:
Entropy0:
HELF:
PopPlusEnt:
DistinctPopular:
EMostPopular:
  - epsilon: 0.2
Entropy:
LogPopEnt:
TinUCB:
  - alpha: 0.2
