MovieLens 100k (B):
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 300
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
MovieLens 1M (B):
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
MovieLens 1M:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
MovieLens 10M:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
Good Books:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
Yahoo Music:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
Yahoo Music Sampled:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
MovieLens 10M Sampled:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
Good Books Sampled:
  NICF:
          parameters:
                  time_step: 3
                  latent_factor: 10
                  learning_rate: 0.01
                  training_epoch: 30000
                  rnn_layer: 1
                  inner_epoch: 50
                  batch: 128
                  gamma: 0.0
                  clip_param: 0.2
                  restore_model: false
                  num_blocks: 2
                  num_heads: 1
                  dropout_rate: 0.1
  PTS:
    parameters:
      num_particles: 2
      var: 0.5
      var_u: 1.0
      var_v: 1.0
      num_lat: 2
  COFIBA:
    parameters:
      alpha: 1
      alpha_2: 1
      num_lat: 10
  ThompsonSampling:
    parameters:
      alpha_0: 1
      beta_0: 1
  Random:
  kNNBandit:
  ALMostPopular:
  OurMethod1:
    parameters:
      alpha: 1.0
      stop: null
      weight_method: 'change'
      num_lat: 10
  OurMethod2:
    parameters:
      alpha: 1.0
      num_lat: 10
  MostPopular:
  LinearUCB:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      alpha: 1.0
      num_lat: 10
  LinEGreedy:
    parameters:
      epsilon: 0.1
      num_lat: 10
  LinUCB:
    parameters:
      alpha: 1.0
      num_lat: 10
  PPELPE:
  UCBLearner:
    parameters:
      stop: 14
      num_lat: 10
  GLM_UCB:
    parameters:
      c: 1.0
      num_lat: 10
  LinearEGreedy:
    parameters:
      epsilon: 0.1
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  LinearThompsonSampling:
    parameters:
      var: 0.05
      user_var: 0.01
      item_var: 0.01
      stop_criteria: 0.0009
      iterations: 20
      num_lat: 10
  EGreedy:
    parameters:
      epsilon: 0.1
  UCB:
    parameters:
      c: 1.0
  MostRepresentative:
  ALEntropy:
  Entropy0:
  HELF:
  PopPlusEnt:
  DistinctPopular:
  EMostPopular:
    parameters:
      epsilon: 0.2
  Entropy:
  LogPopEnt:
  TinUCB:
    parameters:
      alpha: 0.2
