NICF:
  name: NICF
PTS:
  name: PTS
Random:
  name: Random
LinUCB:
  name: LinUCB (MF)
OurMethod1:
  name: Old UCB-Learner
OurMethod2:
  name: WSCB
LinearUCB:
  name: Linear UCB (PMF)
COFIBA:
  name: COFIBA
ThompsonSampling:
  name: TS
kNNBandit:
  name: kNN-Bandit
MostPopular:
  name: Most Popular
LinEGreedy:
  name: Linear ε-Greedy (MF)
PPELPE:
  name: PPELPE
UCBLearner:
  name: UCB-Learner (MF)
GLM_UCB:
  name: GLM-UCB (PMF)
LinearEGreedy:
  name: Linear ε-Greedy (PMF)
LinearThompsonSampling:
  name: Linear TS (PMF)
EGreedy:
  name: ε-Greedy
UCB:
  name: UCB
MostRepresentative:
  name: Most Representative
Entropy0:
  name: Entropy0
HELF:
  name: HELF
PopPlusEnt:
  name: Pop+Ent
DistinctPopular:
  name: Distinct Popular
EMostPopular:
  name: ε-Most Popular
Entropy:
  name: Entropy
LogPopEnt:
  name: log(Pop)⋅Ent
